#!/bin/bash
DIR=/data/streaming/nodejs
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NODE_PATH=/usr/local/lib/node_modules
NODE=/usr/local/bin/node

test -x $NODE || exit 0

function start_app {
  NODE_ENV=production nohup "$NODE" "$DIR/api.js" 1>>"/var/log/streaming-nodejs.log" 2>&1 &
  echo $! > "/var/run/streaming-nodejs.pid"
}

function stop_app {
  kill `cat /var/run/streaming-nodejs.pid`
}

case $1 in
   start)
      start_app ;;
    stop)
      stop_app ;;
    restart)
      stop_app
      start_app
      ;;
    *)
      echo "usage: start|stop" ;;
esac
exit 0

